server:
  port: ${PORT:8081}
  error:
    include-stacktrace: NEVER
    include-binding-errors: NEVER

logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: microservice-stateless-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${BD_PORT:5432}/${DB_NANE:auth-db}
    username: ${BD_USER:postgres}
    password: ${BD_PASSWORD:postgres}
    tomcat:
      max-active: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgres